# fly.toml app configuration file generated for zxcv on 2023-10-19T23:07:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zxcv"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
